import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated from the docs/ folder structure, deliberately.
 *
 * Both folders and files carry numeric prefixes (01-, 02-). Docusaurus strips them from URLs and
 * sidebar labels, and Obsidian's file explorer sorts alphabetically, so the vault tree and the site
 * sidebar read in the SAME order for free. That is why there is no sidebar_position frontmatter and
 * no _category_.json anywhere: the ordering lives in the filenames, where both tools can see it.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
